var fourSyllable = [
    
	"acceptation",
	"accompaniment",
	"activity",
	"adolescence",
	"alligator",
	"alphabetize",
	"America",
	"American",
	"anybody",
	"apologize",
	"appreciate",
	"arbitrary",
	"architecture",
	"area code",
	"asparagus",
	"authority",
	"automobile",
	"avocado",
	"babysitter",
	"banana split",
	"barbecue chips",
	"cafeteria",
	"calculator",
	"capitalize",
	"category",
	"caterpillar",
	"cauliflower",
	"celebration",
	"centimetre",
	"certificate",
	"characterize",
	"chocolate cake",
	"chocolate chip",
	"circulation",
	"combustible",
	"commentator",
	"congratulate",
	"conurbation",
	"conversation",
	"cooperate",
	"dandelion",
	"delicacy",
	"demarcation",
	"demonstration",
	"demonstrative",
	"departmental",
	"development",
	"dictionary",
	"discovery",
	"economize",
	"elementary",
	"elevator",
	"eligible",
	"enthusiast",
	"escalator",
	"expectation",
	"explanation",
	"generally",
	"geography",
	"gingerbread man",
	"gradually",
	"grand piano",
	"gymnasium",
	"helicopter",
	"historical",
	"horse–back riding",
	"hot-air balloon",
	"identity",
	"idiotic",
	"importation",
	"impossible",
	"invisible",
	"irritable",
	"kindergarten",
	"laboratory",
	"librarian",
	"macaroni",
	"memorable",
	"misunderstand",
	"motorcycle",
	"mountain climbing",
	"musical chairs",
	"obedient",
	"obligatory",
	"operator",
	"orthography",
	"paper towel",
	"peanut butter",
	"photographer",
	"poison ivy",
	"police station",
	"potato chips",
	"preferable",
	"preoccupied",
	"preparatory",
	"questionable",
	"raspberry bush",
	"refrigerate",
	"relocation",
	"roller skating",
	"salad dressing",
	"similitude",
	"situation",
	"strawberry bush",
	"supermarket",
	"telephone book",
	"television",
	"temperature",
	"testimony",
	"thermometer",
	"tomato juice",
	"tomato soup",
	"tortilla chips",
	"understanding",
	"unicycle",
	"unusual",
	"vacuum cleaner",
	"variation",
	"vegetable",
	"vice president",
	"vice principal",
	"videogame",
	"vitamin C",
	"washing machine",
	"watermelon"

]