var fiveSyllable = [
    
	"abolitionist",
	"abominable",
	"abomination",
	"accelerator",
	"alliteration",
	"alphabetical",
	"anniversary",
	"apocalypse",
	"apologetic",
	"appreciation",
	"archaeology",
	"aristocracy",
	"auditorium",
	"cafeteria",
	"California",
	"cannibalism",
	"capitalism",
	"characteristic",
	"classification",
	"commensalism",
	"communication",
	"communicative",
	"condominium",
	"congratulations",
	"consideration",
	"Constantinople",
	"continuation",
	"cooperation",
	"curiosity",
	"decontaminate",
	"denominator",
	"diabolical",
	"differentiate",
	"disagreeable",
	"discrimination",
	"disobedient",
	"disorganization",
	"electricity",
	"elementary",
	"enthusiastic",
	"figuratively",
	"generosity",
	"hippopotamus",
	"imagination",
	"immediately",
	"inadequacy",
	"incinerator",
	"inevitable",
	"invigilator",
	"laboratory",
	"magnifying glass",
	"mathematical",
	"Mediterranean",
	"misunderstanding",
	"multiplication",
	"organization",
	"Pennsylvania",
	"personality",
	"photosynthesis",
	"planetarium",
	"pledge of allegiance",
	"potato salad",
	"predisposition",
	"preoccupation",
	"puritanism",
	"qualification",
	"refrigerator",
	"rehabilitate",
	"saltwater taffy",
	"self-preservation",
	"serendipity",
	"sophisticated",
	"South America",
	"sporadically",
	"syllabication",
	"underestimate",
	"unforgettable",
	"unidentified",
	"university",
	"unquestionable",
	"vegetarian",
	"veterinarian",
	"vice presidency",
	"vocabulary"
    
]